from ytmusicapi import YTMusic
import time

# 1. Authenticate
# Ensure you have run 'ytmusicapi setup' in your terminal first to generate oauth.json
yt = YTMusic("oauth.json") 

def create_yt_playlist(name, description="Generated by MelodyMind"):
    """
    Creates a new empty playlist on YouTube Music.
    """
    print(f"🔨 Creating playlist '{name}'...")
    playlist_id = yt.create_playlist(title=name, description=description)
    print(f"✅ Playlist created! ID: {playlist_id}")
    return playlist_id

def search_and_add_song(playlist_id, song_name, artist_name):
    """
    Searches for a song and adds the top result to the playlist.
    Returns True if successful.
    """
    query = f"{song_name} by {artist_name}"
    print(f"🔍 Searching for: {query}...")
    
    # Filter 'songs' ensures we don't get music videos or fan uploads
    search_results = yt.search(query, filter="songs")
    
    if not search_results:
        print(f"❌ Could not find: {query}")
        return False

    # The first result is usually the best match
    best_match = search_results[0]
    video_id = best_match['videoId']
    title_found = best_match['title']
    
    print(f"   -> Found: '{title_found}' (ID: {video_id})")
    
    try:
        yt.add_playlist_items(playlist_id, [video_id])
        print("   -> Added to playlist.")
        return True
    except Exception as e:
        print(f"   -> Error adding song: {e}")
        return False

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    # 1. Mock Data (In the real app, this comes from your Spotify function)
    spotify_tracks = [
        {"artist": "Pink Floyd", "song": "Time"},
        {"artist": "Kendrick Lamar", "song": "Humble"},
        {"artist": "Tame Impala", "song": "The Less I Know The Better"},
        {"artist": "Unknown Artist 123", "song": "Fake Song Example"} # To test failure
    ]

    # 2. Create the Destination Playlist
    new_playlist_id = create_yt_playlist("MelodyMind Transfer #1")

    # 3. Transfer Loop
    success_count = 0
    for track in spotify_tracks:
        success = search_and_add_song(
            new_playlist_id, 
            track['song'], 
            track['artist']
        )
        if success:
            success_count += 1
        
        # Rate Limiting: Be nice to Google's servers!
        time.sleep(1)

    print("\n" + "="*30)
    print(f"🎉 Transfer Complete!")
    print(f"Successful: {success_count}/{len(spotify_tracks)}")
    print("="*30)